site_name: Django Content Settings
nav:
  - Home: index.md
  - Getting Started: first.md
  - Setting Types and Attributes: types.md
  - Using Variables in your project: access.md
  - Permissions: permissions.md
  - Defaults Context: defaults.md
  - API & Views: api.md
  - Available Django Settings: settings.md
  - User Interface for Django Admin: ui.md
  - How Caching is Organized: caching.md
  - User Defined Variables: uservar.md
  - Cookbook: cookbook.md
  - Frequently Asked Questions: faq.md
  - Changelog: changelog.md
  - Glossary: glossary.md
  - How to contribute: contribute.md
  - Source Doc: source.md
theme: readthedocs
repo_url: https://github.com/occipital/django-content-settings/