site_name: Django Content Settings
nav:
  - Home: index.md
  - Getting Started: first.md
  - Variable Types and Attributeses: types.md
  - Using Variables in your project: access.md
  - User Defined Variables: uservar.md
  - "[wip] Custom Type": custom.md
  - Enhancements to Admin Panel: admin.md
  - Permissions: permissions.md
  - Defaults Context: defaults.md
  - API & Views: api.md
  - Available Settings: settings.md
  - How Caching is Organized: caching.md
  - Cookbook: cookbook.md
  - Frequently Asked Questions: faq.md
  - Changelog: changelog.md
  - Glossary: glossary.md
  - "[wip] How to contribute": contribute.md
  - Source Doc: source.md
theme: readthedocs
repo_url: https://github.com/occipital/django-content-settings/